server:
  port: 8080
  servlet.context-path: /api/v1/KidsParty

spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booking_kids_party_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    
#email sender 
  mail:
    host: smtp.gmail.com
    port: 587
    username: bookingkidsparties@gmail.com
    password: udmjktrodqnnzdeu
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true


spring.devtools.remote.restart.enabled: false

spring.servlet.multipart.max-file-size: 5MB

STRIPE_SECRET_KEY: sk_test_51L96moCadxqwLTZTMyoZNqstmJ1XG8BHXqO2PUB0LhE12NFUrSLSbZU2GFxxnVkFMU5fNHbN9LfhVkuww0furSFB00zOW7bBNC